// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payments.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (
    correlation_id, amount, requested_at, processor
) VALUES (
    ?, ?, ?, ?
)
`

type CreatePaymentParams struct {
	CorrelationID string
	Amount        int64
	RequestedAt   int64
	Processor     int64
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.exec(ctx, q.createPaymentStmt, createPayment,
		arg.CorrelationID,
		arg.Amount,
		arg.RequestedAt,
		arg.Processor,
	)
	return err
}
