// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AggregatePaymentsByProcessorAndDateRange(ctx context.Context, arg AggregatePaymentsByProcessorAndDateRangeParams) ([]AggregatePaymentsByProcessorAndDateRangeRow, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
}

var _ Querier = (*Queries)(nil)
